#!/bin/bash

. e2e/variables

echo -e "Starting Grafana Server E2E Scenario"

./e2e/kill-server

mkdir $RUNDIR

echo -e "Copying grafana backend files to temp dir..."

startDockerContainer () {
  echo "Found docker file"

  docker load -i $DOCKER_FILE

  mkdir logs

  docker run -d --rm \
    -p $PORT:3000  \
    -v logs:/var/log/grafana \
    "grafana/grafana:pr-${CIRCLE_SHA1}"
}

startLocalBinary() {
  echo "Copying local dev files"

  cp -r ./bin $RUNDIR
  cp -r ./public $RUNDIR

  mkdir $RUNDIR/conf
  cp ./conf/defaults.ini $RUNDIR/conf/defaults.ini
  cp ./conf/sample.ini $RUNDIR/conf/custom.ini

  $RUNDIR/bin/grafana-server \
    --homepath=$RUNDIR \
    --pidfile=$RUNDIR/pid \
    cfg:server.http_port=$PORT \
    cfg:log.level=debug \
    2>&1 > $RUNDIR/output.log &
}

if [ -f $DOCKER_FILE ]; then
  startDockerContainer
else
  startLocalBinary
fi
